### ISSUE TITLE
When a file is open for add, you get a prompt to check it out after every edit/save.

### ISSUE THREAD

**Issue by jnbmoffa** [botman99/P4SimpleScc#4]
Every file that's opened for add exhibits this behaviour. Would be nice if it detected files that are being added and didn't prompt to check them out.

Can be worked around by disabling the "Prompt for permission..." setting, but I like being prompted in the correct circumstances.

**Comment by botman99** [comment]
Oh, interesting.  I'll see if I can look into that this weekend.

**Comment by botman99** [comment]
This should now be fixed in Version 1.9.  This has also been updated in the Visual Studio Marketplace and should automatically update in Visual Studio if it was installed from the Marketplace.

Thank you for reporting this issue.  :)
