### ISSUE TITLE
Support a mode which could detect config file in project root to specify the workspace

### ISSUE THREAD

**Issue by godot42x** [botman99/P4SimpleScc#5]
I'm working in the environment that have multiple p4 workspaces.

So I think it's better to read some file like `.p4config` on the project root of the solution files, and then  automatically specify the configuration. 

So it could be automatically check to right configuration, instead of by editing extension configuration or using `p4 set....`

**Comment by botman99** [comment]
So, if I understand correctly, you have multiple .sln files in a single folder and those solutions are using different workspaces?  P4SimpleScc stores the settings in the solution variables and should be solution specific.  You can set one of the solutions to use the .p4config file and you can set all of the other solutions to use 'Manual Settings' and set the port, user and client for that solution.  You should only have to set this once for each solution, so you don't need to keep applying these settings.

I don't think enough people would use this type of setup to make it worth having a special mode to support this.

**Comment by godot42x** [comment]
Yes, thanks! The solution configuration is enough for multiple workspaces works.
